##### The Basic

Why is Numpy faster?
- faster to read less bytes of memory
- No type checking when iterating through objects
- contiguous memory

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a)
# fit the datatype for efficient as possible

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]], dtype='int16')
print(b)

[[9 8 7]
 [6 5 4]]


In [4]:
# Get Dimension
a.ndim

1

In [5]:
# Get Shape
print(a.shape)
print(a)

(3,)
[1 2 3]


In [6]:
# Get Type
a.dtype

dtype('int64')

In [7]:
# Get Size
a.itemsize
# it's different by dtype

8

In [8]:
# Get total size
a.nbytes    # = a.size * a.itemsize

24

In [9]:
# axis
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(arr)
print(np.min(arr, axis=0))
print(np.min(arr, axis=1))
print(np.min(arr, axis=2))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[1 2]
 [3 4]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [10]:
arr = np.array([[1, 2], [3, 4]])
print(np.min(arr, axis=0))

[1 2]


##### Accessing/ Changing specific elements, rows, columns, etc

In [11]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 15]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 15]]


In [12]:
a.shape

(2, 7)

In [13]:
# Get a specific element [r, c]
print(a[1, 5])

13


In [14]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [16]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a[0, 0:4:2])
a[1, 2] = 0
print(a)
a[:, 4] = [15, 15]
print(a)
a[0, :] = [7, 7, 7, 7, 7]
print(a)

[1 3]
[[ 1  2  3  4  5]
 [ 6  7  0  9 10]]
[[ 1  2  3  4 15]
 [ 6  7  0  9 15]]
[[ 7  7  7  7  7]
 [ 6  7  0  9 15]]


In [17]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([7, 7])

In [18]:
a[1, 4] = 20
print(a)

a[:, 2] = [1, 2]
print(a)

[[ 7  7  7  7  7]
 [ 6  7  0  9 20]]
[[ 7  7  1  7  7]
 [ 6  7  2  9 20]]


*3-d example

In [19]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# Get a specific element (work outside in)
print(b[0, 1, :])

[3 4]


In [21]:
# replace
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


##### Initializing Different Types of Arrays

In [22]:
# All 0s matrix
print(np.zeros((2, 2, 2)))  

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [23]:
# Any other number
np.full((2, 2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [24]:
# Any other number (full_like)
np.full_like(a, 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [25]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.66552667, 0.10329835],
       [0.10537939, 0.59373677],
       [0.70424827, 0.46335886],
       [0.41167908, 0.77884131]])

In [26]:
# Random integer values
np.random.randint(4, 7, size=(3, 3), dtype='int16')

array([[4, 6, 6],
       [5, 4, 4],
       [6, 6, 5]], dtype=int16)

In [27]:
# The identity matrix
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
# Repeat an array
arr = np.array([1, 2, 3])
arr1 = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
r2 = np.repeat(arr1, 3, axis=0)
print(r1)
print(r2)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [29]:
a = np.full((5, 5), 1)
a[1:4, 1:4] = 0
a[2, 2] = 9
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [30]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

output[1:-1, 1:4] = z   # -1 == 4 same result
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
a = np.array([1, 2, 3])
b = a   # not value but exactly copy the address
b[0] = 100
print(a, b)

c = a.copy()
c[0] = 10
print(a, c)

[100   2   3] [100   2   3]
[100   2   3] [10  2  3]


##### Mathematics

In [32]:
a = np.array([[1, 2, 3, 4]])
print(a)
print(a.shape)

[[1 2 3 4]]
(1, 4)


In [33]:
a + 2

array([[3, 4, 5, 6]])

In [34]:
a - 2

array([[-1,  0,  1,  2]])

In [35]:
a * 2

array([[2, 4, 6, 8]])

In [36]:
a / 2

array([[0.5, 1. , 1.5, 2. ]])

In [37]:
b = np.array([1, 0, 1, 0])
a + b

array([[2, 2, 4, 4]])

In [38]:
a ** 2

array([[ 1,  4,  9, 16]])

In [39]:
# Take the sin
print(np.sin(a))

[[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]]


##### Linear Algebra

In [40]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [41]:
# 행렬의 곱

a = np.array([[1, 2, 3, 4]])
b = np.array([[6], [7], [8], [9]])

print(a * b)
print(b * a)
print(a @ b)
print(b @ a)
print(b.shape)

[[ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]
 [ 9 18 27 36]]
[[ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]
 [ 9 18 27 36]]
[[80]]
[[ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]
 [ 9 18 27 36]]
(4, 1)


In [42]:
a = np.ones((3, 3))
b = np.full((3, 3), 2)
b[1, 1] = 4
print(a * b)

[[2. 2. 2.]
 [2. 4. 2.]
 [2. 2. 2.]]


In [43]:
# Find the determinant

c = np.identity(3, dtype='int8')
print(c)
print(np.linalg.det(c))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
1.0


##### Statistics

In [44]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
print(np.min(stats))

1


In [46]:
print(np.max(stats, axis=1))

[3 6]


In [47]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [68]:
print(np.quantile(stats, 1))

6


In [ ]:
print(np.mean(stats))

3.5


In [75]:
print(np.std(stats))

1.707825127659933


##### Reorganizing Arrays

In [49]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((2, 2, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [76]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

v3 = np.vstack([v1, v2, v1])

In [79]:
print(np.hstack((v3, np.vstack((v2, v1, v2)))))

[[1 2 3 4 5 6 7 8]
 [5 6 7 8 1 2 3 4]
 [1 2 3 4 5 6 7 8]]


In [51]:
# Horizontal stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

##### Miscellaneous
> Load Data from File

In [80]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advances Indexing

In [81]:
print(filedata > 50)

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]


In [82]:
print(filedata[filedata > 50])

[196  75 766  75  55 999  78  76  88]


In [55]:
# you can index with a list in Numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [56]:
print(np.any(filedata > 50, axis=0))
print(np.all(filedata > 50, axis=0))

[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[False False False False  True False False False False False False False
 False False False False False False]


In [57]:
(~(filedata > 50)) & (filedata < 100)   # ~: not

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [58]:
# Problem no.1
a = np.array([1, 2, 3, 4, 5])
arr = np.vstack((a, a + 5, a + 10, a + 15, a + 20, a + 25))
print(arr)

arr[2:4, 0:2]
arr[arr % 6 == 2][:-1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([ 2,  8, 14, 20])

##### Broadcasting
> 차원이 다른 배열끼리 연산할 때 NumPy가 자동으로 모양을 맞춰준다.

In [83]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])

a + b

array([[11, 22],
       [13, 24]])

In [60]:
# sum, mean, max, min
a = np.array([1, 2, 3, 4])

print(a > 2)
print(a[a > 2])

print(a.sum())
print(a.mean())
print(a.max(), a.min())

[False False  True  True]
[3 4]
10
2.5
4 1


##### Linear Algebra

In [61]:
# 원소 곱, 행렬 곱
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

print(A * B)

print(np.matmul(A, B))
print(A @ B)

[[2 0]
 [3 8]]
[[ 4  4]
 [10  8]]
[[ 4  4]
 [10  8]]


In [84]:
A = np.array([[1, 2], [3, 4]])

print(np.transpose(A))      # 전치
print((np.linalg.inv(A)))   # 역행렬
print(np.eye(3))            # 3x3 단위행렬
print('--------------')

print(np.linalg.eig(A))     # 고유값, 고유벡터

[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [63]:
# Ax = b
A = np.array([[2, 1], [3, 2]])
B = np.array([5, 8])

print(np.linalg.solve(A, B))

[2. 1.]


In [85]:
# SVD   / singular value decomposition
A = np.array([[2, 1], [3, 2]])

# A = U @ np.diag(S) @ Vt
U, S, Vt = np.linalg.svd(A)

print(U)
print('-----------------------------')
print(S)
print('-----------------------------')
print(Vt)

[[-0.52573111 -0.85065081]
 [-0.85065081  0.52573111]]
-----------------------------
[4.23606798 0.23606798]
-----------------------------
[[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]
