##### The Basic

Why is Numpy faster?
- faster to read less bytes of memory
- No type checking when iterating through objects
- contiguous memory

In [15]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3], dtype='int32')
a
# fit the datatype for efficient as possible

array([1, 2, 3], dtype=int32)

In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
# Get Dimension
a.ndim

1

In [ ]:
# Get Shape
b.shape

(3,)

In [12]:
# Get Type
a.dtype

dtype('int64')

In [ ]:
# Get Size
a.itemsize
# it's different by dtype

2

In [23]:
# Get total size
a.nbytes    # = a.size * a.itemsize

12

In [137]:
# axis
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(arr)
print(np.min(arr, axis=0))
print(np.min(arr, axis=1))
print(np.min(arr, axis=2))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[1 2]
 [3 4]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]


##### Accessing/ Changing specific elements, rows, columns, etc

In [27]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 15]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 15]]


In [28]:
a.shape

(2, 7)

In [29]:
# Get a specific element [r, c]
a[1, 5]

np.int64(13)

In [30]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [37]:
a[1, 5] = 20
print(a)

a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 15]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 15]]


*3-d example

In [38]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
# Get a specific element (work outside in)
print(b[0, 1, :])

[3 4]


In [42]:
# replace
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


##### Initializing Different Types of Arrays

In [47]:
# All 0s matrix
np.zeros((4, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [50]:
# Any other number
np.full((2, 2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [53]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [54]:
# Random decimal numbers
np.random.rand(4, 2)

array([[5.08842066e-04, 5.05846180e-02],
       [1.53829355e-01, 2.82488814e-01],
       [9.77200478e-04, 8.97725858e-01],
       [6.33338970e-01, 6.09807669e-01]])

In [69]:
# Random integer values
np.random.randint(4, 7, size=(3, 3), dtype='int16')

array([[5, 5, 6],
       [4, 4, 5],
       [5, 5, 5]], dtype=int16)

In [ ]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
# Repeat an array
arr = np.array([1, 2, 3])
arr1 = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
r2 = np.repeat(arr1, 3, axis=0)
print(r1)
print(r2)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [98]:
a = np.full((5, 5), 1)
a[1:4, 1:4] = 0
a[2, 2] = 9
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

output[1:-1, 1:4] = z   # -1 == 4 same result
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a = np.array([1, 2, 3])
b = a   # not value but exactly copy the address
b[0] = 100
print(a, b)

c = a.copy()
c[0] = 10
print(a, c)

[100   2   3] [100   2   3]
[100   2   3] [10  2  3]


##### Mathematics

In [115]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [107]:
a + 2

array([3, 4, 5, 6])

In [108]:
a - 2

array([-1,  0,  1,  2])

In [109]:
a * 2

array([2, 4, 6, 8])

In [110]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [116]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [118]:
a ** 2

array([ 1,  4,  9, 16])

In [ ]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##### Linear Algebra

In [122]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
a = np.ones((3, 3))
b = np.full((3, 3), 2)
b[1, 1] = 4
print(a * b)

array([[2., 2., 2.],
       [2., 4., 2.],
       [2., 2., 2.]])

In [126]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

##### Statistics

In [127]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

array([1, 4])

In [140]:
np.max(stats, axis=1)

array([3, 6])

In [132]:
np.sum(stats, axis=0)

array([5, 7, 9])

##### Reorganizing Arrays

In [146]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((2, 2, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [149]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [150]:
# Horizontal stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

##### Miscellaneous
> Load Data from File

In [157]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

##### Boolean Masking and Advances Indexing

In [158]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [159]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [163]:
# you can index with a list in Numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [172]:
print(np.any(filedata > 50, axis=0))
print(np.all(filedata > 50, axis=0))

[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[False False False False  True False False False False False False False
 False False False False False False]


In [ ]:
(~(filedata > 50)) & (filedata < 100)   # ~: not

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [198]:
# Problem no.1
a = np.array([1, 2, 3, 4, 5])
arr = np.vstack((a, a + 5, a + 10, a + 15, a + 20, a + 25))
print(arr)

arr[2:4, 0:2]
arr[arr % 6 == 2][:-1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([ 2,  8, 14, 20])